# Reff: http://wiki.ros.org/costmap_2d
global_costmap:
    global_frame: map
    update_frequency: 2.0
    publish_frequency: 1.0

    obstacle_range: 5.0
    raytrace_range: 5.0
    static_map: true

    width: 8.0
    height: 8.0