# Reff: http://wiki.ros.org/base_local_planner
base_local_planner: base_local_planner/TrajectoryPlannerROS

TrajectoryPlannerROS:
    min_vel_x: 0.1
    max_vel_x: 0.3
    min_vel_theta: -0.7
    max_vel_theta: 0.7
    min_in_place_vel_theta: 0.4
    escape_vel: -0.1
  
    acc_lim_theta: 1.0
    acc_lim_x: 1.0
    
    holonomic_robot: false

    xy_goal_tolerance: 0.15
    yaw_goal_tolerance: 0.2

    meter_scoring: true
    path_distance_bias: 1.5
    goal_distance_bias: 0.8
    occdist_scale:  0.02

    sim_time: 1.5